# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'  

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 2
  minor: 2
  patch: $[counter(variables['minor'], 0)] #this will reset when we bump minor
  NugetVersion: $(major).$(minor).$(patch)

stages:
  - stage: Build
    displayName: Build and publish
    jobs:
    - job: job
      steps:
        - template: build.yml